spring:
    application:
        name: Chat App
    data:
        web:
            pageable:
                default-page-size: 10
                max-page-size: 50
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

chat:
    rabbitmq:
        queue: chatQueue
        exchange: chatExchange
        routingkey: chatRoutingKey