spring:
    application:
        name: Chat App
    data:
        web:
            pageable:
                default-page-size: 10
                max-page-size: 50
        jpa:
            repositories:
                bootstrap-mode: deferred
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            # modify batch size as necessary
            hibernate.jdbc.batch_size: 25
            hibernate.order_inserts: true
            hibernate.order_updates: true
            hibernate.query.fail_on_pagination_over_collection_fetch: true
            hibernate.query.in_clause_parameter_padding: true
        hibernate:
            ddl-auto: update

    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest

chat:
    rabbitmq:
        queue: chatQueue
        exchange: chatExchange
        routingkey: chatRoutingKey