spring:
    application:
        name: Chat App
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: ${DB_USERNAME:sa}
        password: ${CHATAPP_DB_PASSWORD:password}

    rabbitmq:
        host: ${CHATAPP_RABBITMQ_HOST:127.0.0.1}
        port: ${CHATAPP_RABBITMQ_PORT:5672}
        username: ${CHATAPP_RABBITMQ_USERNAME:guest}
        password: ${CHATAPP_RABBITMQ_PASSWORD:guest}

chat:
    rabbitmq:
        queue: ${CHATAPP_RABBITMQ_PASSWORD:chatQueue}
        exchange: ${CHATAPP_RABBITMQ_PASSWORD:chatExchange}
        routingkey: ${CHATAPP_RABBITMQ_PASSWORD:chatRoutingKey}